### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by StromanStroman** [SujeathPareddy/MLS#1]
It's poor documentation.I don't know how to it,I can not see effect.
Now os is macos mojave,IDE is xcode.
Could you tell me how to run the project?

i run cmake,and get results:
CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "FindPCL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PCL", but
  CMake did not find one.

  Could not find a package configuration file provided by "PCL" (requested
  version 1.3) with any of the following names:

    PCLConfig.cmake
    pcl-config.cmake

  Add the installation prefix of "PCL" to CMAKE_PREFIX_PATH or set "PCL_DIR"
  to a directory containing one of the above files.  If "PCL" provides a
  separate development package or SDK, be sure it has been installed.

**Comment by SujeathPareddy** [comment]
Apologies. When I made this repo I didn't think anyone would actually use it.

I've added build instructions in the README. I think all you need to do is to ```brew install pcl```.
